<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Unit;
use App\Models\Product;
use App\Models\Picture;
use App\Models\ProductMovement;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\DB;

class RealProductSeeder extends Seeder
{
    public function run(): void
    {
        $sourceDir = 'C:\\xampp\\htdocs\\VitalCare\\image\\product_images';
        $destDir = storage_path('app/public/products');
        $frontendDestDir = base_path('../frontend/public/storage/products');

        // Ensure target directories exist
        if (!File::exists($destDir)) {
            File::makeDirectory($destDir, 0755, true);
        }
        if (!File::exists($frontendDestDir)) {
            File::makeDirectory($frontendDestDir, 0755, true);
        }

        // 1. Create or retrieve Units
        $unitNames = ['Strip', 'Box', 'Bottle', 'Piece', 'Sachet', 'Tube', 'Tablet'];
        $units = [];
        foreach ($unitNames as $u) {
            $units[$u] = Unit::firstOrCreate(['name' => $u])->id;
        }

        // 2. Create or retrieve Categories
        $categoryNames = [
            'Pain & Fever Relief',
            'Cold, Cough & Flu',
            'Allergy & Antihistamines',
            'Vitamins & Supplements',
            'Topical & First Aid',
            'Digestive & Rehydration',
            'Eye Care',
            'Medical Devices & Diagnostics'
        ];
        $categories = [];
        foreach ($categoryNames as $c) {
            $categories[$c] = Category::firstOrCreate(['name' => $c])->id;
        }

        // 3. Complete list of 62 products mapped to images
        $productsData = [
            // --- Pain & Fever Relief ---
            [
                'name' => 'Biogesic 500mg Tablets',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Strip',
                'price' => 1500,
                'dosage' => '500mg',
                'usage' => 'Take 1-2 tablets every 4-6 hours as needed for fever or pain. Do not exceed 8 tablets in 24 hours.',
                'side_effects' => 'Rare, mild skin rash or upset stomach. Avoid excessive alcohol while taking paracetamol.',
                'description' => 'Biogesic is a trusted paracetamol formula for fast, effective relief of headaches, fever, toothache, and body aches.',
                'images' => ['biogesic_1.jpg', 'biogesic_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 120,
            ],
            [
                'name' => 'Biogesic 120mg/5ml Infant Drops',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Bottle',
                'price' => 3200,
                'dosage' => '120mg/5ml',
                'usage' => 'Use the calibrated dropper provided. Dose according to child body weight or pediatrician instructions.',
                'side_effects' => 'Gentle on stomach. Consult doctor if fever persists over 48 hours.',
                'description' => 'Gentle paracetamol drops formulated specifically for infants with pleasant fruit flavor and precise dropper.',
                'images' => ['biogesic_120_1.png'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 50,
            ],
            [
                'name' => 'Biogesic 250mg/5ml Kids Suspension',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Bottle',
                'price' => 3800,
                'dosage' => '250mg/5ml',
                'usage' => 'Children 2-6 yrs: 5ml; 7-12 yrs: 5-10ml every 4-6 hours. Shake well before use.',
                'side_effects' => 'Rare allergic rash. Do not combine with other paracetamol products.',
                'description' => 'Great-tasting orange flavored paracetamol syrup designed for children to quickly reduce fever and aches.',
                'images' => ['biogesic_250_1.jpg', 'biogesic_250_2.jpg', 'biogesic_250_3.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 65,
            ],
            [
                'name' => 'Alaxan Tablets',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Strip',
                'price' => 2500,
                'dosage' => 'Paracetamol 325mg + Ibuprofen 200mg',
                'usage' => 'Take 1 tablet every 6 hours after meals with water. Do not take on an empty stomach.',
                'side_effects' => 'Stomach irritation, mild nausea, dizziness. Take with food or milk.',
                'description' => 'Dual action formula combining Paracetamol and Ibuprofen for targeted, powerful relief of muscle aches and arthritis.',
                'images' => ['alaxan_1.jpg', 'alaxan-2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 90,
            ],
            [
                'name' => 'Alaxan FR Fast-Release Capsules',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Strip',
                'price' => 3000,
                'dosage' => 'Paracetamol 325mg + Ibuprofen 200mg',
                'usage' => 'Take 1 capsule every 6 hours after meals. Maximum 4 capsules in 24 hours.',
                'side_effects' => 'Mild indigestion. Avoid if you have active stomach ulcers.',
                'description' => 'Alaxan FR features a fast-release formulation that absorbs quickly to treat acute muscle stiffness, sprains, and backaches.',
                'images' => ['alaxan_fr_1.jpg', 'alaxan_fr_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 85,
            ],
            [
                'name' => 'Gofen 400 Softgels',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Strip',
                'price' => 4500,
                'dosage' => 'Ibuprofen 400mg',
                'usage' => 'Take 1 clear softgel capsule every 8 hours immediately after food.',
                'side_effects' => 'Heartburn, stomach upset. Drink plenty of water.',
                'description' => 'Liquid-filled softgel Ibuprofen 400mg from Mega We Care for fast relief of migraine, dental pain, and dysmenorrhea.',
                'images' => ['gofen_1.jpg', 'gofen_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 70,
            ],
            [
                'name' => 'Paracap 500mg Caplets',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Strip',
                'price' => 1200,
                'dosage' => '500mg Paracetamol',
                'usage' => '1 to 2 caplets every 4-6 hours as needed. Maximum 8 caplets per day.',
                'side_effects' => 'Very rare. Safe for most adults when following dosage limits.',
                'description' => 'Smooth coated 500mg paracetamol caplet designed for effortless swallowing and rapid headache relief.',
                'images' => ['paracap_1.jpg', 'paracap_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 100,
            ],
            [
                'name' => 'Diclofenac Sodium 50mg Tablets',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Strip',
                'price' => 2000,
                'dosage' => '50mg',
                'usage' => 'Take 1 tablet 2 to 3 times daily strictly after meals with water.',
                'side_effects' => 'Gastric irritation, indigestion. Contraindicated in severe ulcer disease.',
                'description' => 'Enteric-coated non-steroidal anti-inflammatory drug (NSAID) prescribed for osteoarthritis, rheumatoid arthritis, and joint pain.',
                'images' => ['diclofenac_1.jpg', 'diclofenac_2.jpg'],
                'requires_prescription' => true,
                'is_chronic' => false,
                'stock' => 60,
            ],
            [
                'name' => 'Diclofenac Suppository',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Box',
                'price' => 6500,
                'dosage' => '50mg rectally',
                'usage' => 'Insert 1 suppository rectally as directed by physician. For rectal use only.',
                'side_effects' => 'Local rectal irritation, burning sensation.',
                'description' => 'Fast-acting rectal suppository providing systemic analgesia when oral administration is not possible.',
                'images' => ['diclo_suppo.jpg'],
                'requires_prescription' => true,
                'is_chronic' => false,
                'stock' => 40,
            ],
            [
                'name' => 'Paracetamol 250mg Suppositories',
                'category' => 'Pain & Fever Relief',
                'unit' => 'Box',
                'price' => 4500,
                'dosage' => '250mg',
                'usage' => 'Insert 1 suppository rectally every 6 hours for children experiencing fever with active vomiting.',
                'side_effects' => 'Mild local sensitivity.',
                'description' => 'Pediatric antipyretic suppositories for emergency fever control when oral syrups are rejected or vomited.',
                'images' => ['para_suppo_250.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 35,
            ],

            // --- Cold, Cough & Flu ---
            [
                'name' => 'Decolgen Cold & Flu Tablets',
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Strip',
                'price' => 1800,
                'dosage' => 'Paracetamol 500mg, Phenylpropanolamine 25mg, Chlorpheniramine 2mg',
                'usage' => 'Take 1 tablet every 6 hours with a glass of water.',
                'side_effects' => 'May cause sleepiness or dry mouth. Do not drive or operate heavy machinery.',
                'description' => 'Complete cold tablet formula that unblocks congested noses, stops runny nose and sneezing, and relieves fever.',
                'images' => ['decolgen_1.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 110,
            ],
            [
                'name' => 'Decolgen Extra Forte',
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Strip',
                'price' => 2200,
                'dosage' => '1 caplet every 6 hours',
                'usage' => 'For severe nasal sinus congestion, fever, and throbbing cold headaches.',
                'side_effects' => 'Mild drowsiness, dry throat.',
                'description' => 'Extra-strength decongestant and pain relieving caplet for heavy seasonal flu and sinus blockage.',
                'images' => ['decolgen_extra.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 80,
            ],
            [
                'name' => 'Fluza Cold & Flu Capsules',
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Strip',
                'price' => 2500,
                'dosage' => '1 capsule 3 times daily after meals',
                'usage' => 'For symptomatic relief of fever, headache, body chills, and nasal catarrh.',
                'side_effects' => 'Mild lethargy. Stay hydrated.',
                'description' => 'Fast-acting cold & flu capsule providing multi-symptom relief throughout the day.',
                'images' => ['fluza_1.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 75,
            ],
            [
                'name' => 'Afrin Adult Nasal Spray 15ml',
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Bottle',
                'price' => 8500,
                'dosage' => 'Oxymetazoline HCl 0.05%',
                'usage' => '2-3 sprays in each nostril every 10-12 hours. Do not use for more than 3-5 consecutive days.',
                'side_effects' => 'Temporary stinging, sneezing, or nasal dryness.',
                'description' => '12-Hour powerful adult nasal decongestant pump spray that unblocks severely congested sinuses in seconds.',
                'images' => ['afrin_a_1.jpg', 'afrin_a_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 45,
            ],
            [
                'name' => 'Afrin Paediatric Nasal Spray 15ml',
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Bottle',
                'price' => 8000,
                'dosage' => 'Oxymetazoline HCl 0.025%',
                'usage' => '1-2 sprays in each nostril twice daily for children 2-6 years. Max 3 days.',
                'side_effects' => 'Mild local tickle or sneeze.',
                'description' => 'Gentle pediatric strength nasal spray to help congested babies and children breathe easily through the night.',
                'images' => ['afrin_p_1.jpg', 'afrin_p_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 40,
            ],
            [
                'name' => 'Chericof Cough Syrup 100ml',
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Bottle',
                'price' => 4200,
                'dosage' => 'Adults: 10ml 3 times daily; Children: 5ml 3 times daily',
                'usage' => 'Take after food. Soothes throat irritation and calms stubborn, hacking coughs.',
                'side_effects' => 'Mild sedation, dry mouth.',
                'description' => 'Comprehensive cough syrup that suppresses dry cough and soothes inflamed respiratory passages.',
                'images' => ['chericof_syrup.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 60,
            ],
            [
                'name' => 'Chericof Herbal Lozenges',
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Strip',
                'price' => 1500,
                'dosage' => 'Dissolve 1 lozenge slowly in mouth every 2-3 hours',
                'usage' => 'For scratchy sore throat, voice strain, and cough irritation.',
                'side_effects' => 'None under normal use.',
                'description' => 'Herbal throat lozenges enriched with natural menthol to immediately coat and soothe raw throat tissues.',
                'images' => ['chericof_lozenge.jpg', 'chericof_lozenge_1.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 90,
            ],
            [
                'name' => "Woods Peppermint Expectorant (Blue)",
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Bottle',
                'price' => 5500,
                'dosage' => 'Adults: 10ml; Children 6-12: 5ml every 4 hours',
                'usage' => 'For productive cough with thick, stubborn bronchial mucus and chest tightness.',
                'side_effects' => 'Mild nausea if taken on empty stomach.',
                'description' => "Woods Peppermint Blue expectorant contains Guaiphenesin to thin and loosen thick chest phlegm.",
                'images' => ['wood_syrup_blue.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 55,
            ],
            [
                'name' => "Woods Peppermint Cough Relief (Red)",
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Bottle',
                'price' => 5500,
                'dosage' => 'Adults: 10ml; Children 6-12: 5ml every 4 hours',
                'usage' => 'For persistent non-productive dry cough and allergic throat tickles.',
                'side_effects' => 'Mild drowsiness.',
                'description' => "Woods Peppermint Red formula provides immediate cough reflex suppression for peaceful sleep.",
                'images' => ['wood_syrup_red.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 50,
            ],
            [
                'name' => "Woods Peppermint Lozenges",
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Strip',
                'price' => 1800,
                'dosage' => 'Dissolve 1 lozenge slowly in mouth. Max 8 daily.',
                'usage' => 'Immediate cooling comfort for hoarse throat and raspy voice.',
                'side_effects' => 'None.',
                'description' => 'Invigorating peppermint pastilles that keep the throat moist and refreshed.',
                'images' => ['wood_lozenge_1.jpg', 'wood_lozenge_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 80,
            ],
            [
                'name' => 'Konidin Herbal Cough Lozenges',
                'category' => 'Cold, Cough & Flu',
                'unit' => 'Strip',
                'price' => 1200,
                'dosage' => 'Dissolve 1 lozenge slowly as needed',
                'usage' => 'Relieves smoker cough, throat dryness, and mild throat irritation.',
                'side_effects' => 'None.',
                'description' => 'Herbal cough lozenges with traditional botanical extracts for easy daily throat care.',
                'images' => ['konidin_lozenge_1.jpg', 'konidin_lozenge_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 95,
            ],

            // --- Allergy & Antihistamines ---
            [
                'name' => 'Burmeton 4mg Blister Pack',
                'category' => 'Allergy & Antihistamines',
                'unit' => 'Strip',
                'price' => 800,
                'dosage' => 'Chlorpheniramine Maleate 4mg',
                'usage' => 'Take 1 tablet every 4-6 hours. Max 24mg in 24 hours.',
                'side_effects' => 'Marked drowsiness, dry mouth. Do not drive or drink alcohol.',
                'description' => 'Classic fast-acting antihistamine for acute allergic reactions, allergic rhinitis, hives, and itchy skin.',
                'images' => ['burmeton_card_1.jpg', 'burmeton_card_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 150,
            ],
            [
                'name' => 'Burmeton 4mg 100s Bottle',
                'category' => 'Allergy & Antihistamines',
                'unit' => 'Bottle',
                'price' => 6000,
                'dosage' => 'Chlorpheniramine Maleate 4mg',
                'usage' => 'Take 1 tablet every 4-6 hours as needed for allergy symptoms.',
                'side_effects' => 'Drowsiness, reduced alertness.',
                'description' => 'Economy 100-tablet bottle of Chlorpheniramine Maleate 4mg for long-term household allergy care.',
                'images' => ['burmeton_100_1.jpg', 'burmeton_100_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 40,
            ],
            [
                'name' => "Cetrin 10mg Tablets (Dr. Reddy's)",
                'category' => 'Allergy & Antihistamines',
                'unit' => 'Strip',
                'price' => 3500,
                'dosage' => 'Cetirizine Hydrochloride 10mg',
                'usage' => 'Take 1 tablet once daily in the evening with water.',
                'side_effects' => 'Low sedation risk, mild dry throat.',
                'description' => "Dr. Reddy's Cetrin provides full 24-hour relief from pollen allergies, chronic urticaria, and perennial hay fever.",
                'images' => ['cetrin_dr.reddy.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 90,
            ],
            [
                'name' => 'Alerday 5mg Levocetirizine',
                'category' => 'Allergy & Antihistamines',
                'unit' => 'Strip',
                'price' => 4000,
                'dosage' => 'Levocetirizine 5mg',
                'usage' => 'Take 1 tablet once daily before bedtime.',
                'side_effects' => 'Minimal drowsiness compared to first-generation antihistamines.',
                'description' => 'Pure R-enantiomer antihistamine offering higher potency and reduced sleepiness for severe seasonal allergies.',
                'images' => ['alerday.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 80,
            ],
            [
                'name' => 'PB Lora 10mg Loratadine',
                'category' => 'Allergy & Antihistamines',
                'unit' => 'Strip',
                'price' => 3200,
                'dosage' => 'Loratadine 10mg',
                'usage' => 'Take 1 tablet once daily in the morning with water.',
                'side_effects' => 'True non-drowsy formulation under standard dosage.',
                'description' => 'Non-sedating daytime antihistamine allowing normal work and driving while relieving nasal allergy symptoms.',
                'images' => ['pb_lora_1.jpg', 'pb_lora_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 75,
            ],
            [
                'name' => 'Lensen Antihistamine Syrup',
                'category' => 'Allergy & Antihistamines',
                'unit' => 'Bottle',
                'price' => 3800,
                'dosage' => 'Children 2-6: 2.5ml once daily; 6-12: 5ml daily',
                'usage' => 'For childhood allergic rhinitis, eczema itchiness, and allergic sneezing.',
                'side_effects' => 'Well tolerated, slight drowsiness.',
                'description' => 'Fruit flavored pediatric antihistamine syrup for gentle, effective relief of children allergy symptoms.',
                'images' => ['lensen_syrup.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 45,
            ],

            // --- Vitamins & Supplements ---
            [
                'name' => 'Enervon-C Multivitamin Tablets',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Strip',
                'price' => 3000,
                'dosage' => 'Vitamin C 500mg + Vitamin B-Complex',
                'usage' => 'Take 1 tablet daily with or after meals.',
                'side_effects' => 'Harmless bright yellow urine due to Vitamin B2.',
                'description' => 'High-potency Vitamin C (500mg) combined with B-Complex vitamins to boost immunity and physical stamina.',
                'images' => ['enervon_c.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 120,
            ],
            [
                'name' => 'Vitacap Daily Multivitamin',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Box',
                'price' => 12500,
                'dosage' => '1 softgel capsule daily with breakfast',
                'usage' => 'For general health maintenance, active lifestyle support, and dietary deficiency prevention.',
                'side_effects' => 'Take with meal to optimize fat-soluble vitamin absorption.',
                'description' => 'Mega We Care premium multivitamin softgels containing 16 essential vitamins and minerals for daily wellness.',
                'images' => ['vitacap.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 60,
            ],
            [
                'name' => 'Vitahome Complete Formula',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Bottle',
                'price' => 15000,
                'dosage' => '1 tablet daily after food',
                'usage' => 'Daily nutritional insurance for adults and seniors to maintain energy and vitality.',
                'side_effects' => 'None reported.',
                'description' => 'Balanced daily multivitamin with antioxidants and trace minerals for everyday nutritional replenishment.',
                'images' => ['vitahome_1.jpg', 'vitahome_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 50,
            ],
            [
                'name' => 'Vitamin B-Complex Denk (Germany)',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Box',
                'price' => 18000,
                'dosage' => '1 tablet daily with adequate fluid',
                'usage' => 'For prevention and treatment of Vitamin B deficiencies, nerve numbness, and neuropathy.',
                'side_effects' => 'Well tolerated pharmaceutical grade formula.',
                'description' => 'Premium German neurotropic B-vitamin complex for peripheral nerve repair and cellular energy metabolism.',
                'images' => ['vit_b_denk.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 40,
            ],
            [
                'name' => 'Appeton Lysine 60s Tablets',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Bottle',
                'price' => 16500,
                'dosage' => 'Children 1-8: 1 chewable tablet; 9+: 1-2 tablets daily',
                'usage' => 'Chewable tablet with L-Lysine to boost appetite and healthy weight gain in growing children.',
                'side_effects' => 'None reported under standard use.',
                'description' => 'Star-shaped chewable multivitamin fortified with Lysine to stimulate appetite in picky eating children.',
                'images' => ['appeton_lysine_60.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 35,
            ],
            [
                'name' => 'Appeton Lysine Syrup for Children',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Bottle',
                'price' => 14000,
                'dosage' => 'Children under 4: 2.5ml daily; Over 4: 5ml daily',
                'usage' => 'Appetite enhancing syrup for toddlers and infants with poor eating habits.',
                'side_effects' => 'None.',
                'description' => 'Tasty fruity liquid formula combining Lysine with multivitamins for healthy childhood development.',
                'images' => ['appeton_lysine_syrup.jpg', 'appeton_lysine_syrup_1.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 40,
            ],
            [
                'name' => 'Appeton Multivitamin with Taurine',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Bottle',
                'price' => 17000,
                'dosage' => '1 chewable tablet daily with food',
                'usage' => 'Fortified with Taurine to support brain development, cognitive focus, and eye health in school-age children.',
                'side_effects' => 'None.',
                'description' => 'Cognitive and visual development multivitamin chewables designed for academic and active vitality.',
                'images' => ['appeton_taurine_1.jpg', 'appeton_taurine_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 35,
            ],
            [
                'name' => 'Appeton Multivitamin Pastilles / Jelly',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Box',
                'price' => 8500,
                'dosage' => '1-2 pastilles daily',
                'usage' => 'Chewy vitamin pastilles providing daily Vitamin C support for immune defense.',
                'side_effects' => 'None.',
                'description' => 'Delicious fruit-flavored chewy jelly pastilles that make children look forward to taking their daily vitamins.',
                'images' => ['appeton_jelly.jpg', 'appeton_jelly_1.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 60,
            ],
            [
                'name' => 'Becoactin Tablets (Appetite Stimulant)',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Strip',
                'price' => 2500,
                'dosage' => '1 tablet twice daily 30 minutes before food',
                'usage' => 'For treating loss of appetite, convalescence recovery, and nutritional rehabilitation.',
                'side_effects' => 'Mild initial drowsiness that usually subsides after a few days.',
                'description' => 'Proven Cyproheptadine and B-Vitamin combination that stimulates hunger and aids in healthy weight recovery.',
                'images' => ['becoactin_card_1.jpg', 'becoactin_card_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 80,
            ],
            [
                'name' => 'Becoactin Syrup 100ml',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Bottle',
                'price' => 5000,
                'dosage' => 'Children: 5ml twice daily 30 minutes before meals',
                'usage' => 'Liquid appetite stimulant for underweight children and poor eaters.',
                'side_effects' => 'May cause slight sleepiness.',
                'description' => 'Sweet liquid appetite enhancer designed to support steady weight gain in pediatric care.',
                'images' => ['becoactin_syrup_1.jpg', 'becoactin_syrup_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 45,
            ],
            [
                'name' => 'Cyprocal Calcium & Appetite Syrup',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Bottle',
                'price' => 6000,
                'dosage' => '5-10ml daily before meals',
                'usage' => 'Dual action Calcium, Vitamin D3, and appetite stimulants for growing children.',
                'side_effects' => 'Mild drowsiness.',
                'description' => 'Promotes strong bone mineralization and healthy appetite in toddlers and young children.',
                'images' => ['cyprocal_syrup_1.jpg', 'cyprocal_syrup_2.jpg', 'cyprocal_syrup_3.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 50,
            ],
            [
                'name' => 'Ensure Gold Nutritional Powder 850g',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Box',
                'price' => 68000,
                'dosage' => 'Mix 6 level scoops with 185ml of lukewarm water. 1-2 servings daily.',
                'usage' => 'Complete, balanced medical nutrition with HMB and protein to rebuild muscle strength and bone density.',
                'side_effects' => 'Not for parenteral use or galactosemia.',
                'description' => 'Abbott Ensure Gold adult nutritional milk powder with 28 vitamins, minerals, and prebiotic FOS.',
                'images' => ['esnure_850_1.jpg', 'ensure_850_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 30,
            ],
            [
                'name' => 'Ensure Gold Single Sachet 53.5g',
                'category' => 'Vitamins & Supplements',
                'unit' => 'Sachet',
                'price' => 4500,
                'dosage' => 'Mix 1 sachet into 185ml lukewarm water',
                'usage' => 'Portable single serving complete adult nutrition for hospital visits or travel.',
                'side_effects' => 'None.',
                'description' => 'Single-serving Ensure Gold Vanilla sachet providing complete protein, vitamins, and minerals on the go.',
                'images' => ['ensure_sachet.jpg', 'ensure_sachet_1.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 100,
            ],

            // --- Topical & First Aid ---
            [
                'name' => 'Difelene Topical Gel 30g',
                'category' => 'Topical & First Aid',
                'unit' => 'Tube',
                'price' => 4500,
                'dosage' => 'Apply 3-4 times daily to painful area',
                'usage' => 'For acute joint pain, tendonitis, sports sprains, and backache.',
                'side_effects' => 'Rare mild skin irritation.',
                'description' => 'Topical Diclofenac Diethylamine gel that deeply penetrates inflamed joint tissues for targeted pain relief.',
                'images' => ['difelene_1.jpg', 'difelene_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 60,
            ],
            [
                'name' => 'Voltex-C Topical Gel',
                'category' => 'Topical & First Aid',
                'unit' => 'Tube',
                'price' => 4000,
                'dosage' => 'Massage gently over affected muscles 3 times daily',
                'usage' => 'Relieves neck stiffness, shoulder tension, and sports contusions.',
                'side_effects' => 'Wash hands after application.',
                'description' => 'Fast-acting anti-inflammatory analgesic gel enriched with soothing camphor and menthol.',
                'images' => ['voltex_c_1.jpg', 'voltex_c_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 55,
            ],
            [
                'name' => 'Tiger Balm Medicated Plaster (Standard)',
                'category' => 'Topical & First Aid',
                'unit' => 'Box',
                'price' => 4500,
                'dosage' => 'Apply 1 plaster to clean, dry skin once or twice daily',
                'usage' => 'For stiff neck, backache, arthritic joint pain, and muscular fatigue.',
                'side_effects' => 'Mild warm tingling sensation.',
                'description' => 'Ventilated hydrogel plaster infused with world-famous Tiger Balm herbal essential oils.',
                'images' => ['tiger_balm_plaster_1.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 70,
            ],
            [
                'name' => 'Tiger Balm Plaster Cool',
                'category' => 'Topical & First Aid',
                'unit' => 'Box',
                'price' => 5000,
                'dosage' => 'Apply to sore muscles. Replace after 8 hours.',
                'usage' => 'Cooling relief for acute sports injuries, bruises, and sudden sprains.',
                'side_effects' => 'Cool sensation.',
                'description' => 'Hydrogel cool plaster delivering hours of refreshing relief to inflamed, strained muscle fibers.',
                'images' => ['tiger_balm_plaster_c_1.jpg', 'tiger_balm_plaster_c_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 65,
            ],
            [
                'name' => 'Tiger Balm Plaster Warm',
                'category' => 'Topical & First Aid',
                'unit' => 'Box',
                'price' => 5000,
                'dosage' => 'Apply to chronic lower back or shoulder stiffness',
                'usage' => 'Warm soothing heat to stimulate local blood flow and soothe chronic joint aches.',
                'side_effects' => 'Slight skin warmth.',
                'description' => 'Deep heat hydrogel patch for persistent muscle knots, chronic rheumatism, and lumbar stiffness.',
                'images' => ['tiger_balm_plaster_w_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 65,
            ],
            [
                'name' => 'Dettol Antiseptic Liquid 250ml',
                'category' => 'Topical & First Aid',
                'unit' => 'Bottle',
                'price' => 7500,
                'dosage' => 'Dilute 1 cap in 400ml water for antiseptic washing',
                'usage' => 'Antiseptic cleansing of wounds, cuts, bites, abrasions, and clinical disinfection.',
                'side_effects' => 'Do not apply undiluted directly to open wounds.',
                'description' => 'Hospital-grade chloroxylenol disinfectant liquid killing 99.9% of bacteria and infection-causing germs.',
                'images' => ['dettol.jpg_Default-WorkingFormat_1000Wx1000H'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 50,
            ],
            [
                'name' => 'Physiodose Sterile Saline Ampoules',
                'category' => 'Topical & First Aid',
                'unit' => 'Box',
                'price' => 8500,
                'dosage' => '1 single-dose ampoule for nasal or eye irrigation',
                'usage' => 'Gentle nasal cleansing in infants and sterile contact lens / eye washing.',
                'side_effects' => 'Safe, preservative-free sterile 0.9% sodium chloride.',
                'description' => 'Made in France sterile single-dose saline solution flacons for pediatric respiratory and eye hygiene.',
                'images' => ['physiodose_1.jpg', 'physiodose_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 40,
            ],
            [
                'name' => 'Antibacterial Wet Wipes',
                'category' => 'Topical & First Aid',
                'unit' => 'Box',
                'price' => 3500,
                'dosage' => 'Pull single sheet and wipe surfaces or hands',
                'usage' => 'Hand hygiene, mobile screen disinfection, and travel sanitization.',
                'side_effects' => 'Avoid direct contact with eyes.',
                'description' => 'Soft, durable wet wipes killing 99.9% of bacteria with soothing aloe vera essence.',
                'images' => ['wet_tissue_1.jpg', 'wet_tissue_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 75,
            ],
            [
                'name' => 'Alcohol Hand Sanitizer Gel 500ml',
                'category' => 'Topical & First Aid',
                'unit' => 'Bottle',
                'price' => 5500,
                'dosage' => 'Dispense 1 pump and rub hands together until dry',
                'usage' => 'Instant waterless antiseptic hand sanitizing for clinics and households.',
                'side_effects' => 'Flammable. For external use only.',
                'description' => '75% Ethyl Alcohol hospital-grade sanitizing gel with moisturizers to keep skin soft.',
                'images' => ['hand_sanitizer_l.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 60,
            ],
            [
                'name' => 'Pocket Hand Sanitizer Spray 50ml',
                'category' => 'Topical & First Aid',
                'unit' => 'Bottle',
                'price' => 2000,
                'dosage' => 'Spray 2-3 mists onto palms and rub thoroughly',
                'usage' => 'Compact pocket disinfectant for transit, dining, and daily travel.',
                'side_effects' => 'None.',
                'description' => 'Portable 75% alcohol hand sanitizer mist spray for convenient daily germ protection.',
                'images' => ['hand_sanitizer_s_1.jpg', 'hand_sanitizer_s_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 90,
            ],

            // --- Eye Care ---
            [
                'name' => 'Clear Eye Lubricating Eye Drops',
                'category' => 'Eye Care',
                'unit' => 'Bottle',
                'price' => 3500,
                'dosage' => 'Instill 1-2 drops in affected eye(s) 3-4 times daily',
                'usage' => 'Soothing relief from dry eye irritation, computer screen strain, and dust exposure.',
                'side_effects' => 'Transient mild blurring right after application.',
                'description' => 'Sterile soothing artificial tears drop formula providing immediate comfort for tired, strained eyes.',
                'images' => ['clear_eye_eye_drop.jpg', 'clear_eye_eye_drop_1.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 70,
            ],
            [
                'name' => 'Gentamycin Antibiotic Eye/Ear Drops',
                'category' => 'Eye Care',
                'unit' => 'Bottle',
                'price' => 4000,
                'dosage' => '1-2 drops in affected eye/ear every 4 hours',
                'usage' => 'Treatment of bacterial conjunctivitis, blepharitis, and external ear canal bacterial infections.',
                'side_effects' => 'Temporary stinging. Complete the prescribed course.',
                'description' => 'Potent broad-spectrum aminoglycoside antibiotic drops for treating ocular and aural bacterial infections.',
                'images' => ['gentamycin_eye_drop_1.jpg', 'gentamycin_eye_drop_2.jpg'],
                'requires_prescription' => true,
                'is_chronic' => false,
                'stock' => 50,
            ],

            // --- Digestive & Rehydration ---
            [
                'name' => 'Royal-D Electrolyte Drink Sachet',
                'category' => 'Digestive & Rehydration',
                'unit' => 'Sachet',
                'price' => 800,
                'dosage' => 'Dissolve 1 sachet in 250ml cold drinking water',
                'usage' => 'Rapid electrolyte and energy replenishment during sports, sweating, or heat exhaustion.',
                'side_effects' => 'None.',
                'description' => 'Electrolyte energy powder formulated with sodium, potassium, and glucose for rapid hydration.',
                'images' => ['royal_d_1.jpg', 'royal_d_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 200,
            ],
            [
                'name' => 'ORS Orange Electrolyte Sachet',
                'category' => 'Digestive & Rehydration',
                'unit' => 'Sachet',
                'price' => 1000,
                'dosage' => 'Dissolve packet in 1000ml (1 liter) of potable water',
                'usage' => 'Prevention and clinical treatment of dehydration caused by diarrhea and vomiting.',
                'side_effects' => 'Do not boil the prepared mixture.',
                'description' => 'WHO-standard Oral Rehydration Salts with orange flavor for pediatric and adult fluid recovery.',
                'images' => ['ors_orange.jpg', 'ors_orange_1.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 180,
            ],

            // --- Medical Devices & Diagnostics ---
            [
                'name' => 'Omron Automatic Blood Pressure Monitor',
                'category' => 'Medical Devices & Diagnostics',
                'unit' => 'Piece',
                'price' => 145000,
                'dosage' => 'One-touch automatic reading',
                'usage' => 'Place cuff around upper arm at heart level while seated at rest. Press start button.',
                'side_effects' => 'None.',
                'description' => 'Clinically validated Japanese upper-arm digital blood pressure monitor with hypertension & irregular heartbeat alert.',
                'images' => ['omron_pressure_cuff.jpg'],
                'requires_prescription' => false,
                'is_chronic' => true,
                'refill_interval_days' => 365,
                'stock' => 20,
            ],
            [
                'name' => 'Citizen Digital Blood Pressure Monitor',
                'category' => 'Medical Devices & Diagnostics',
                'unit' => 'Piece',
                'price' => 125000,
                'dosage' => 'Digital oscillometric measurement',
                'usage' => 'Easy-to-use digital upper arm blood pressure meter with 90-memory log for tracking home readings.',
                'side_effects' => 'None.',
                'description' => 'Reliable Japanese engineered blood pressure monitor featuring large high-contrast LCD and cuff error sensor.',
                'images' => ['citizen_pressure_cuff_1.jpg', 'citizen_pressure_cuff_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => true,
                'refill_interval_days' => 365,
                'stock' => 25,
            ],
            [
                'name' => 'Thada Blood Glucose Meter Kit',
                'category' => 'Medical Devices & Diagnostics',
                'unit' => 'Piece',
                'price' => 65000,
                'dosage' => 'Requires 0.5 µL capillary blood drop. Results in 5 seconds.',
                'usage' => 'Daily blood glucose self-monitoring for diabetes management. Includes lancing pen and lancets.',
                'side_effects' => 'Sterilize fingertip prior to lancing.',
                'description' => 'Complete home diabetes monitoring kit with strip ejector, pre/post meal markers, and USB memory log.',
                'images' => ['thada_glucometer_1.jpg', 'thada_glucometer_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => true,
                'refill_interval_days' => 90,
                'stock' => 30,
            ],
            [
                'name' => 'Thada Blood Glucose Test Strips 50s',
                'category' => 'Medical Devices & Diagnostics',
                'unit' => 'Box',
                'price' => 38000,
                'dosage' => 'Single use test strip',
                'usage' => 'Insert strip into Thada meter before applying blood droplet. Close vial tightly after opening.',
                'side_effects' => 'Store between 4°C - 30°C in a dry environment.',
                'description' => '50-count replacement test strips for Thada blood glucose meter with auto-coding technology.',
                'images' => ['thada_strip.jpg'],
                'requires_prescription' => false,
                'is_chronic' => true,
                'refill_interval_days' => 30,
                'stock' => 50,
            ],
            [
                'name' => 'Digital Clinical Thermometer',
                'category' => 'Medical Devices & Diagnostics',
                'unit' => 'Piece',
                'price' => 6500,
                'dosage' => 'Oral or axillary temperature measurement (60s)',
                'usage' => 'Place under tongue or armpit until beep sounds. Clean sensor with alcohol after use.',
                'side_effects' => 'None. Mercury-free.',
                'description' => 'Fast, safe, and accurate electronic clinical thermometer with fever alarm beep and auto shut-off.',
                'images' => ['thermometer_digital_1.jpg', 'thermometer_digital_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 80,
            ],
            [
                'name' => 'Non-Contact Infrared Forehead Thermometer',
                'category' => 'Medical Devices & Diagnostics',
                'unit' => 'Piece',
                'price' => 35000,
                'dosage' => 'Hold 1-3 cm from center of forehead and press trigger',
                'usage' => 'Touchless 1-second body temperature screening with tri-color fever backlight.',
                'side_effects' => 'Hygienic and radiation-free.',
                'description' => 'Medical grade infrared non-contact thermometer ideal for sleeping babies and clinic entryway screening.',
                'images' => ['thermometer_infared.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 30,
            ],
            [
                'name' => 'N95 Protective Respirator Mask',
                'category' => 'Medical Devices & Diagnostics',
                'unit' => 'Box',
                'price' => 15000,
                'dosage' => 'Fit tightly over mouth and nose with dual head straps',
                'usage' => 'High filtration protection against viral aerosols, PM2.5 particulate pollution, and smoke.',
                'side_effects' => 'Ensure proper fit to avoid air leakage.',
                'description' => 'Certified 5-layer N95 particulate respirator mask with cushioned nose bridge seal.',
                'images' => ['95_mask_1.jpg', '95_mask_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 60,
            ],
            [
                'name' => '3-Ply Surgical Face Mask (Box of 50)',
                'category' => 'Medical Devices & Diagnostics',
                'unit' => 'Box',
                'price' => 6000,
                'dosage' => 'Single use disposable mask',
                'usage' => 'Daily protection against respiratory droplets, dust, and airborne contaminants.',
                'side_effects' => 'Discard when moist or soiled.',
                'description' => 'Box of 50 certified 3-layer meltblown surgical face masks with comfortable soft ear loops.',
                'images' => ['face_mask_1.jpg', 'face_mask_2.jpg'],
                'requires_prescription' => false,
                'is_chronic' => false,
                'stock' => 100,
            ],
        ];

        $totalSeeded = 0;
        $totalImagesCopied = 0;

        DB::beginTransaction();
        try {
            foreach ($productsData as $data) {
                // Create or update Product
                $product = Product::updateOrCreate(
                    ['name' => $data['name']],
                    [
                        'category_id' => $categories[$data['category']] ?? null,
                        'unit_id' => $units[$data['unit']] ?? null,
                        'price' => $data['price'],
                        'dosage' => $data['dosage'],
                        'usage' => $data['usage'],
                        'side_effects' => $data['side_effects'],
                        'description' => $data['description'],
                        'minimum_quantity' => 10,
                        'is_published' => true,
                        'requires_prescription' => $data['requires_prescription'] ?? false,
                        'is_chronic' => $data['is_chronic'] ?? false,
                        'refill_interval_days' => $data['refill_interval_days'] ?? null,
                    ]
                );

                // Handle Images
                if (!empty($data['images'])) {
                    // Remove existing pictures for clean seed
                    Picture::where('product_id', $product->id)->delete();

                    foreach ($data['images'] as $idx => $imgFile) {
                        $srcFile = $sourceDir . DIRECTORY_SEPARATOR . $imgFile;
                        if (File::exists($srcFile)) {
                            $targetFilename = 'prod_' . $product->id . '_' . $imgFile;
                            $destPath = $destDir . DIRECTORY_SEPARATOR . $targetFilename;
                            $frontendDestPath = $frontendDestDir . DIRECTORY_SEPARATOR . $targetFilename;

                            // Copy to backend storage
                            File::copy($srcFile, $destPath);
                            // Also copy to frontend public storage so Vercel frontend can serve statically if needed
                            File::copy($srcFile, $frontendDestPath);

                            Picture::create([
                                'product_id' => $product->id,
                                'image_path' => 'products/' . $targetFilename,
                                'is_primary' => ($idx === 0),
                            ]);
                            $totalImagesCopied++;
                        }
                    }
                }

                // Create initial product movement (stock)
                $existingMovement = ProductMovement::where('product_id', $product->id)
                    ->whereIn('movement_type', ['current', 'stored'])
                    ->first();

                if (!$existingMovement) {
                    ProductMovement::create([
                        'product_id' => $product->id,
                        'supply_product_id' => null,
                        'instock_quantity' => $data['stock'] ?? 50,
                        'manufactured_date' => now()->subMonths(3),
                        'expired_date' => now()->addMonths(18),
                        'movement_type' => 'current',
                        'batch_number' => 'VC-' . strtoupper(substr(md5($product->name), 0, 6)),
                        'purchase_price' => round($data['price'] * 0.7),
                        'sale_price' => $data['price'],
                        'movement_date' => now(),
                        'created_by' => 1,
                    ]);
                }

                $totalSeeded++;
            }

            DB::commit();
            $this->command->info("Successfully seeded {$totalSeeded} products with {$totalImagesCopied} images copied!");
        } catch (\Exception $e) {
            DB::rollBack();
            $this->command->error("Failed seeding products: " . $e->getMessage());
            throw $e;
        }
    }
}
